- name: "needs review"
  color: "fef2c0"
  description: "Review is requested"
- name: "approved"
  color: "e6f7a3"
  description: "Work item is approved to be worked on"
- name: "rejected"
  color: "e4e669"
  description: "Work item is rejected and will not be worked on"
- name: "invalid"
  color: "e4e669"
  description: "Work item details are invalid"
- name: "completed"
  color: "80c932"
  description: "Work item has been completed"
- name: "DM"
  color: "8db1f4"
  description: "Data Movement"
- name: "DBaaS"
  color: "c6acf9"
  description: "Database as a Service"
- name: "CaaS"
  color: "e5e569"
  description: "Compute as a Service"
- name: "GaaS"
  color: "e6f7a3"
  description: "Governance as a Service"
- name: "OB"
  color: "e4e669"
  description: "Observability"
- name: "DTE"
  color: "e4e669"
  description: "DevOps Technical Enablement"
- name: "Runway"
  color: "80c932"
  description: "Developer Experience"
- name: "Squad1"
  color: "80c932"
  description: "Squad"
- name: "Squad2"
  color: "e4e669"
  description: "Squad"
- name: "Squad3"
  color: "7ded61"
  description: "Squad"
- name: "Squad4"
  color: "a3e283"
  description: "Squad"
- name: "Squad5"
  color: "f9dac0"
  description: "Squad"
- name: "Squad6"
  color: "80c932"
  description: "Squad"
- name: "Squad7"
  color: "e4e669"
  description: "Squad"
- name: "Squad8"
  color: "7ded61"
  description: "Squad"
- name: "Squad9"
  color: "a3e283"
  description: "Squad"
- name: "Squad10"
  color: "f9dac0"
  description: "Squad"
- name: "Squad11"
  color: "80c932"
  description: "Squad"
- name: "Squad12"
  color: "e4e669"
  description: "Squad"
- name: "Epic"
  color: "10d17d"
  description: "Large user story 4-6 weeks of work"
- name: "Points: 3"
  color: "1d76db"
  description: "The size of work estimated for implementation"
- name: "Work Type: 4a. Code-Test-Deploy Internal Software"
  color: "ea8a15"
  description: "Labor capitalization"